baseURL = "http://example.org/"
languageCode = "en-us"
title = "Highway Bitcoin"
theme = "startpage"

[[params.searchEngines]]
  name = "Google"
  activated = true
  url = "https://www.google.com/search"
